# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerLogMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(help_text='The message to be shown in the backend.')),
                ('message_type', models.CharField(choices=[('DEBUG', 'DEBUG'), ('ERROR', 'ERROR'), ('INFO', 'INFO')], default='INFO', help_text='The type of log message.', max_length=17)),
                ('object_type', models.CharField(blank=True, choices=[('DEBUG', 'DEBUG'), ('ERROR', 'ERROR'), ('INFO', 'INFO')], help_text='The type of related object, if there is one.', max_length=30, null=True)),
                ('object_id', models.IntegerField(blank=True, help_text='The id of the related object, if there is one.', null=True)),
            ],
        ),
    ]
