# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 00:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20161023_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalassociation',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalclub',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalcompetition',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalfavorite',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalgame',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalgameparticipation',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalleague',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalreferee',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalseason',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalteam',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalvenue',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='parent_association',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_associations', to='core.Association', verbose_name='Parent Association'),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, keep_meta=True, null=True, quality=75, size=[500, 500], upload_to='logos/', verbose_name='Club logo'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_competitions', to='core.League', verbose_name='League'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_competitions', to='core.Season', verbose_name='Season'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team', to='core.Team', verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Owner', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='game',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_games', to='core.Competition', verbose_name='Competition'),
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(verbose_name='KickOff'),
        ),
        migrations.AlterField(
            model_name='game',
            name='fsrID',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='FSR ID'),
        ),
        migrations.AlterField(
            model_name='game',
            name='fsrUrl',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='FSR Url'),
        ),
        migrations.AlterField(
            model_name='game',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guestTeam_set', to='core.GameParticipation', verbose_name='Guest Participation'),
        ),
        migrations.AlterField(
            model_name='game',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostTeam_set', to='core.GameParticipation', verbose_name='Host Participation'),
        ),
        migrations.AlterField(
            model_name='game',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Referee', verbose_name='Referee'),
        ),
        migrations.AlterField(
            model_name='game',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Venue', verbose_name='Venue'),
        ),
        migrations.AlterField(
            model_name='gameparticipation',
            name='points',
            field=models.IntegerField(blank=True, null=True, verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='gameparticipation',
            name='redCards',
            field=models.IntegerField(blank=True, null=True, verbose_name='Red Cards'),
        ),
        migrations.AlterField(
            model_name='gameparticipation',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='gameparticipation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team_set', to='core.Team', verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='gameparticipation',
            name='tries',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tries'),
        ),
        migrations.AlterField(
            model_name='historicalassociation',
            name='history_type',
            field=models.CharField(choices=[('+', 'Erzeugt'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalassociation',
            name='parent_association',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.HistoricalAssociation'),
        ),
        migrations.AlterField(
            model_name='historicalclub',
            name='history_type',
            field=models.CharField(choices=[('+', 'Erzeugt'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalcompetition',
            name='history_type',
            field=models.CharField(choices=[('+', 'Erzeugt'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalfavorite',
            name='history_type',
            field=models.CharField(choices=[('+', 'Erzeugt'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalgame',
            name='date',
            field=models.DateTimeField(verbose_name='KickOff'),
        ),
        migrations.AlterField(
            model_name='historicalgame',
            name='fsrID',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='FSR ID'),
        ),
        migrations.AlterField(
            model_name='historicalgame',
            name='fsrUrl',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='FSR Url'),
        ),
        migrations.AlterField(
            model_name='historicalgame',
            name='history_type',
            field=models.CharField(choices=[('+', 'Erzeugt'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalgameparticipation',
            name='history_type',
            field=models.CharField(choices=[('+', 'Erzeugt'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalgameparticipation',
            name='points',
            field=models.IntegerField(blank=True, null=True, verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='historicalgameparticipation',
            name='redCards',
            field=models.IntegerField(blank=True, null=True, verbose_name='Red Cards'),
        ),
        migrations.AlterField(
            model_name='historicalgameparticipation',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='historicalgameparticipation',
            name='tries',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tries'),
        ),
        migrations.AlterField(
            model_name='historicalleague',
            name='history_type',
            field=models.CharField(choices=[('+', 'Erzeugt'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalreferee',
            name='history_type',
            field=models.CharField(choices=[('+', 'Erzeugt'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalseason',
            name='history_type',
            field=models.CharField(choices=[('+', 'Erzeugt'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalteam',
            name='history_type',
            field=models.CharField(choices=[('+', 'Erzeugt'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='historicalvenue',
            name='history_type',
            field=models.CharField(choices=[('+', 'Erzeugt'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1),
        ),
        migrations.AlterField(
            model_name='team',
            name='custom_logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, help_text='Custom team logo.', keep_meta=True, null=True, quality=75, size=[500, 500], upload_to='logos/'),
        ),
    ]
