# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20171004_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalteam',
            name='score_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='score_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
