# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-19 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20171219_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalseason',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='season',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='historicalseason',
            name='fsr_url_slug',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='fsr_url_slug',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
