# Generated by Django 2.1.7 on 2019-04-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20181025_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalleague',
            name='archived',
            field=models.BooleanField(default=False, help_text='Check if league is not active anymore'),
        ),
        migrations.AddField(
            model_name='league',
            name='archived',
            field=models.BooleanField(default=False, help_text='Check if league is not active anymore'),
        ),
    ]
